CREATE SCHEMA EXERCISE_1; 
CREATE TABLE EMP_1
(EMP_NUM CHAR(3),
EMP_LNAME VARCHAR(15),
EMP_FNAME VARCHAR(15),
EMP_HIREDATE DATE,
JOB_CODE CHAR(3));

INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_HIREDATE, JOB_CODE)
VALUES ('1', 'LastName', 'Firstname', '2023-04-13', '501');
INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_HIREDATE, JOB_CODE)
VALUES ('2', 'Operaña', 'Larenz Sandrei',  '2023-04-13', '502');

SELECT * FROM exercise_1.emp_1
WHERE JOB_CODE = '502';